language: python

sudo: required

services:
  - docker

branches:
  only:
  - master

install: true

script: true

after_script:
  - docker build --tag $DOCKER_USERNAME/sentiment-analysis-web-logic .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/sentiment-analysis-web-logic
